POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "nama": "sandi",
    "email": "mardin@gmail.com",
    "password": "sandi123",
    "confermPassword": "sandi123"
}



###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "mardin@gmail.com",
    "password": "mardin123"
}
